/* ─── Tailwind CSS Configuration ──────────────────────────────────── */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container":          "#fcd116",
        "error":                      "#ba1a1a",
        "on-error-container":         "#93000a",
        "on-background":              "#1f1b11",
        "secondary-container":        "#7da0ff",
        "background":                 "#fff8ef",
        "outline":                    "#7f7760",
        "outline-variant":            "#d0c6ab",
        "primary-fixed-dim":          "#ecc300",
        "tertiary":                   "#c0001f",
        "inverse-primary":            "#ecc300",
        "surface-container-lowest":   "#ffffff",
        "primary":                    "#715c00",
        "surface-tint":               "#715c00",
        "tertiary-fixed-dim":         "#ffb3ae",
        "tertiary-fixed":             "#ffdad7",
        "surface-dim":                "#e2d9c8",
        "surface-container":          "#f6eddb",
        "primary-fixed":              "#ffe17b",
        "secondary":                  "#335ab4",
        "tertiary-container":         "#ffc8c4",
        "inverse-surface":            "#343024",
        "on-secondary":               "#ffffff",
        "surface-bright":             "#fff8ef",
        "surface-container-high":     "#f0e7d5",
        "on-primary-container":       "#6e5a00",
        "on-tertiary-container":      "#bb001e",
        "surface":                    "#fff8ef",
        "surface-container-highest":  "#eae2d0",
        "on-surface":                 "#1f1b11",
        "surface-variant":            "#eae2d0",
        "surface-container-low":      "#fcf3e1",
        "on-primary":                 "#ffffff",
        "on-surface-variant":         "#4d4632",
        "on-secondary-container":     "#003387",
        "on-tertiary":                "#ffffff",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body":     ["Be Vietnam Pro", "sans-serif"],
        "label":    ["Be Vietnam Pro", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "full":    "9999px",
      },
    },
  },
};
